Task5 modules an services
Leemvale/angular-mentoring pull request #5
Opened 2019-01-21 20:05 UTC by Leemvale

2019-01-25 12:20 UTC, fat23cat requested changes
Посмотрел пулл реквест, все круто за исключением того, что у тебя не происходит отписка от observable, когда компонент уничтожается. [Почему это важно.](https://netbasal.com/why-its-important-to-unsubscribe-from-rxjs-subscription-a7a6455d6a02)
Так же на счет сервисов. В принципе, если сервис синглтон на уровне модуля, то ок, можно и не отписываться, т.к. он будет существовать пока существует приложение. Но есть кейсы, когда необходимо указывать сервис как провайдер в [компоненте](https://angular.io/guide/providers#limiting-provider-scope-with-components), тогда, при уничтожении компонента подписки удаляться так же не будут.

2019-01-26 13:32 UTC, fat23cat commented on src/app/login/components/login-page/login-page.component.ts
> +    this.authSubscription.unsubscribe();
Новая проблема, если мы перейдем /courses -> /login, и попробуем тут же вернуться назад, то получим:
![image](https://user-images.githubusercontent.com/30126907/51787853-dcc96b00-2187-11e9-81c4-e1bb0a19ad63.png)

2019-01-26 20:18 UTC, Leemvale commented on src/app/login/components/login-page/login-page.component.ts
> +    this.authSubscription.unsubscribe();
Да, поняла почему так происходит, поправила

2019-01-26 20:53 UTC, fat23cat commented on src/app/login/components/login-page/login-page.component.ts
> +export class LoginPageComponent implements OnInit, OnDestroy {
Я бы немного по-другому решил эту проблему. В RxJava есть такая шутка - [CompositeDisposable](http://reactivex.io/RxJava/javadoc/io/reactivex/disposables/CompositeDisposable.html), можно написать свой класс наподобие этого, чтобы переложить логику проверки наличия подписки на него:
```
import { Subscription, TeardownLogic } from 'rxjs';

class CompositeDisposable {
    private subscription: Subscription;
    private isSmbSubscribed: boolean = false;

    constructor() {
        this.subscription = new Subscription();
    }

    public add(subscriber: TeardownLogic): void {
        this.subscription.add(subscriber);
    }

    public unsubscribe(): void {
        if (this.isSmbSubscribed) {
            this.subscription.unsubscribe();
        }
    }
}
```
И использовал как-то так:
```suggestion
export class LoginPageComponent implements OnInit, OnDestroy {
  private anchor: CompositeDisposable;

  loginForm = this.fb.group({
    email: ['', Validators.required],
    password: ['', Validators.required],
  });

  constructor(
    private fb: FormBuilder,
    private router: Router,
    private authorizationService: AuthorizationService,
  ) { }

  ngOnInit(): void {
    this.anchor = new CompositeDisposable();
  }

  ngOnDestroy(): void {
      this.anchor.unsubscribe();
  }

  public onLogin(): void {
    const email = this.loginForm.controls['email'].value;
    const password = this.loginForm.controls['password'].value;
    const login = this.authorizationService.login(email, password).subscribe(
      () => {
        console.log('Logged in!');
        this.router.navigate(['']);
      },
    );
    this.anchor.add(login);
  }
}
```

2019-01-27 13:17 UTC, merged